# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calcus.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 550)
        font = QtGui.QFont()
        font.setPointSize(13)
        MainWindow.setFont(font)
        self.widget = QtWidgets.QWidget(MainWindow)
        self.widget.setObjectName("widget")
        self.label_zero = QtWidgets.QLabel(self.widget)
        self.label_zero.setGeometry(QtCore.QRect(50, 50, 300, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_zero.sizePolicy().hasHeightForWidth())
        self.label_zero.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(False)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_zero.setFont(font)
        self.label_zero.setMouseTracking(False)
        self.label_zero.setTabletTracking(False)
        self.label_zero.setAcceptDrops(False)
        self.label_zero.setToolTipDuration(-2)
        self.label_zero.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_zero.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_zero.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_zero.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_zero.setScaledContents(False)
        self.label_zero.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_zero.setWordWrap(False)
        self.label_zero.setIndent(0)
        self.label_zero.setOpenExternalLinks(False)
        self.label_zero.setObjectName("label_zero")
        self.lavel_default = QtWidgets.QLabel(self.widget)
        self.lavel_default.setGeometry(QtCore.QRect(50, 15, 300, 25))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.lavel_default.setFont(font)
        self.lavel_default.setAlignment(QtCore.Qt.AlignCenter)
        self.lavel_default.setObjectName("lavel_default")
        self.btn_x2 = QtWidgets.QPushButton(self.widget)
        self.btn_x2.setGeometry(QtCore.QRect(25, 425, 100, 75))
        self.btn_x2.setObjectName("btn_x2")
        self.btn_zero = QtWidgets.QPushButton(self.widget)
        self.btn_zero.setGeometry(QtCore.QRect(125, 425, 100, 75))
        self.btn_zero.setObjectName("btn_zero")
        self.btn_comma = QtWidgets.QPushButton(self.widget)
        self.btn_comma.setGeometry(QtCore.QRect(225, 425, 100, 75))
        self.btn_comma.setObjectName("btn_comma")
        self.btn_1 = QtWidgets.QPushButton(self.widget)
        self.btn_1.setGeometry(QtCore.QRect(25, 350, 100, 75))
        self.btn_1.setObjectName("btn_1")
        self.btn_2 = QtWidgets.QPushButton(self.widget)
        self.btn_2.setGeometry(QtCore.QRect(125, 350, 100, 75))
        self.btn_2.setObjectName("btn_2")
        self.btn_3 = QtWidgets.QPushButton(self.widget)
        self.btn_3.setGeometry(QtCore.QRect(225, 350, 100, 75))
        self.btn_3.setObjectName("btn_3")
        self.btn_4 = QtWidgets.QPushButton(self.widget)
        self.btn_4.setGeometry(QtCore.QRect(25, 275, 100, 75))
        self.btn_4.setObjectName("btn_4")
        self.btn_5 = QtWidgets.QPushButton(self.widget)
        self.btn_5.setGeometry(QtCore.QRect(125, 275, 100, 75))
        self.btn_5.setObjectName("btn_5")
        self.btn_6 = QtWidgets.QPushButton(self.widget)
        self.btn_6.setGeometry(QtCore.QRect(225, 275, 100, 75))
        self.btn_6.setObjectName("btn_6")
        self.btn_7 = QtWidgets.QPushButton(self.widget)
        self.btn_7.setGeometry(QtCore.QRect(25, 200, 100, 75))
        self.btn_7.setObjectName("btn_7")
        self.btn_8 = QtWidgets.QPushButton(self.widget)
        self.btn_8.setGeometry(QtCore.QRect(125, 200, 100, 75))
        self.btn_8.setObjectName("btn_8")
        self.btn_9 = QtWidgets.QPushButton(self.widget)
        self.btn_9.setGeometry(QtCore.QRect(225, 200, 100, 75))
        self.btn_9.setObjectName("btn_9")
        self.btn_proc = QtWidgets.QPushButton(self.widget)
        self.btn_proc.setGeometry(QtCore.QRect(25, 125, 100, 75))
        self.btn_proc.setObjectName("btn_proc")
        self.btn_clear = QtWidgets.QPushButton(self.widget)
        self.btn_clear.setGeometry(QtCore.QRect(125, 125, 100, 75))
        self.btn_clear.setObjectName("btn_clear")
        self.bnt_equal = QtWidgets.QPushButton(self.widget)
        self.bnt_equal.setGeometry(QtCore.QRect(225, 125, 100, 75))
        self.bnt_equal.setObjectName("bnt_equal")
        self.btn_back = QtWidgets.QPushButton(self.widget)
        self.btn_back.setGeometry(QtCore.QRect(325, 125, 50, 75))
        self.btn_back.setObjectName("btn_back")
        self.btn_div = QtWidgets.QPushButton(self.widget)
        self.btn_div.setGeometry(QtCore.QRect(325, 200, 50, 75))
        self.btn_div.setObjectName("btn_div")
        self.btn_mult = QtWidgets.QPushButton(self.widget)
        self.btn_mult.setGeometry(QtCore.QRect(325, 275, 50, 75))
        self.btn_mult.setObjectName("btn_mult")
        self.btn_minus = QtWidgets.QPushButton(self.widget)
        self.btn_minus.setGeometry(QtCore.QRect(325, 350, 50, 75))
        self.btn_minus.setObjectName("btn_minus")
        self.btn_plus = QtWidgets.QPushButton(self.widget)
        self.btn_plus.setGeometry(QtCore.QRect(325, 425, 50, 75))
        self.btn_plus.setObjectName("btn_plus")
        MainWindow.setCentralWidget(self.widget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.add_functions()

        self.is_equal = False

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Калькулятор"))
        self.label_zero.setText(_translate("MainWindow", "0"))
        self.lavel_default.setText(_translate("MainWindow", "Обычный"))
        self.btn_x2.setText(_translate("MainWindow", "x²"))
        self.btn_zero.setText(_translate("MainWindow", "0"))
        self.btn_comma.setText(_translate("MainWindow", "."))
        self.btn_1.setText(_translate("MainWindow", "1"))
        self.btn_2.setText(_translate("MainWindow", "2"))
        self.btn_3.setText(_translate("MainWindow", "3"))
        self.btn_4.setText(_translate("MainWindow", "4"))
        self.btn_5.setText(_translate("MainWindow", "5"))
        self.btn_6.setText(_translate("MainWindow", "6"))
        self.btn_7.setText(_translate("MainWindow", "7"))
        self.btn_8.setText(_translate("MainWindow", "8"))
        self.btn_9.setText(_translate("MainWindow", "9"))
        self.btn_proc.setText(_translate("MainWindow", "%"))
        self.btn_clear.setText(_translate("MainWindow", "CE"))
        self.bnt_equal.setText(_translate("MainWindow", "="))
        self.btn_back.setText(_translate("MainWindow", "←"))
        self.btn_div.setText(_translate("MainWindow", "÷"))
        self.btn_mult.setText(_translate("MainWindow", "×"))
        self.btn_minus.setText(_translate("MainWindow", "-"))
        self.btn_plus.setText(_translate("MainWindow", "+"))

    def add_functions(self):
        self.btn_1.clicked.connect(lambda: self.write_number(self.btn_1.text()))
        self.btn_1.setShortcut('1')
        self.btn_2.clicked.connect(lambda: self.write_number(self.btn_2.text()))
        self.btn_2.setShortcut('2')
        self.btn_3.clicked.connect(lambda: self.write_number(self.btn_3.text()))
        self.btn_3.setShortcut('3')
        self.btn_4.clicked.connect(lambda: self.write_number(self.btn_4.text()))
        self.btn_4.setShortcut('4')
        self.btn_5.clicked.connect(lambda: self.write_number(self.btn_5.text()))
        self.btn_5.setShortcut('5')
        self.btn_6.clicked.connect(lambda: self.write_number(self.btn_6.text()))
        self.btn_6.setShortcut('6')
        self.btn_7.clicked.connect(lambda: self.write_number(self.btn_7.text()))
        self.btn_7.setShortcut('7')
        self.btn_8.clicked.connect(lambda: self.write_number(self.btn_8.text()))
        self.btn_8.setShortcut('8')
        self.btn_9.clicked.connect(lambda: self.write_number(self.btn_9.text()))
        self.btn_9.setShortcut('9')
        self.btn_zero.clicked.connect(lambda: self.write_number(self.btn_zero.text()))
        self.btn_zero.setShortcut('0')
        self.btn_comma.clicked.connect(lambda: self.write_number(self.btn_comma.text()))
        self.btn_comma.setShortcut('.')

        self.btn_mult.clicked.connect(self.mult)
        self.btn_mult.setShortcut('*')
        self.btn_div.clicked.connect(self.division)
        self.btn_div.setShortcut('/')
        self.btn_plus.clicked.connect(lambda: self.write_number(self.btn_plus.text()))
        self.btn_plus.setShortcut('+')
        self.btn_minus.clicked.connect(lambda: self.write_number(self.btn_minus.text()))
        self.btn_minus.setShortcut('-')

        self.bnt_equal.clicked.connect(self.results)
        self.bnt_equal.setShortcut('Enter')
        self.btn_back.clicked.connect(self.clear_last_char)
        self.btn_back.setShortcut('Backspace')
        self.btn_x2.clicked.connect(self.square)
        self.btn_x2.setShortcut('Shift+2')
        self.btn_proc.clicked.connect(self.proc)
        self.btn_proc.setShortcut('shift+5')
        self.btn_clear.clicked.connect(self.clear_text)
        self.btn_clear.setShortcut('C')

    def clear_last_char(self):
        text = self.label_zero.text()
        text = text[:-1]
        self.label_zero.setText(text)

    def clear_text(self):
        self.label_zero.clear()

    def mult(self):
        text = self.label_zero.text()
        new_text = text + "*"
        self.label_zero.setText(new_text)

    def division(self):
        text = self.label_zero.text()
        new_text = text + "/"
        self.label_zero.setText(new_text)

    def square(self):
        text = self.label_zero.text()
        try:
            num = float(text)
        except:
            num = 0.0
        result = num ** 2
        self.label_zero.setText(str(result))

    def proc(self):
        text = self.label_zero.text()
        try:
            num = float(text)
            percent = 0.01
            result = num * percent
            self.label_zero.setText(str(result))
        except:
            self.label_zero.setText("Error")

    def write_number(self, number):
        if self.label_zero.text() == '0' or self.is_equal:
            self.label_zero.setText(number)
            self.is_equal = False
        else:
            self.label_zero.setText(self.label_zero.text() + number)

    def results(self):
        text = self.label_zero.text()
        try:
            result = eval(text)
        except:
            result = "Error"
        self.label_zero.setText(str(result))
        self.is_equal = True


# ГОРЯЧИЕ КЛАВИШИ: C - очистить все; backsapce - очистить по символу; кнопки на нампаде для всех цифр, действий,
# и вычисления результата; shift+2 - вычисление квадрата; shift+5 - вычисление процента.
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    MainWindow.setFixedSize(400, 550)
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
